// codes/news_recsys/news_rec_web/react-fun-rec/src/components/BottomBar/index.tsx
import React from 'react'
import {
  useNavigate,
  useLocation,
} from 'react-router-dom'
import { NavBar, TabBar } from 'antd-mobile'

import {
  AppOutline,
  UserOutline,
} from 'antd-mobile-icons'

import  './index.scss'

const BottomBar = () => {
  const navigate = useNavigate()
  const location = useLocation()
  const { pathname } = location

  const setRouteActive = (value: string) => {
    navigate(value, { replace: true }) 
  }

  const tabs = [
    {
      key: '/recLists',
      title: '首页',
      icon: <AppOutline />,
    },
    {
      key: '/mySelf',
      title: '我的',
      icon: <UserOutline />
    },
  ]

  return (
    <TabBar activeKey={pathname} onChange={value => setRouteActive(value)} safeArea>
      {tabs.map(item => (
        <TabBar.Item key={item.key} icon={item.icon} title={item.title} />
      ))}
    </TabBar>
  )
}

export default () => {
  return (
    <div className='bottom'>
      <BottomBar />
    </div>
  )
}

// fun-rec/codes/news_recsys/news_rec_web/vue3-fun-rec/src/components/bottomBar.vue
<template>
  <div class="bottomBar">
    <router-view />
    <van-tabbar route>
      <van-tabbar-item icon="home-o" replace to="/recLists">首页</van-tabbar-item>
      <van-tabbar-item icon="friends-o" replace to="/myself">我的</van-tabbar-item>
    </van-tabbar>
  </div>
</template>

<style scoped>
  .bottomBar {
    position: fixed;
    bottom: 0px;
    width: 100vw;
  }
</style>
