// codes/news_recsys/news_rec_web/react-fun-rec/src/pages/NewsInfo/index.tsx
import { NavBar, Toast } from 'antd-mobile';
import axios from 'axios';
import { useEffect, useState } from 'react'
import { useDispatch } from 'react-redux';
import { useLocation, useNavigate } from 'react-router-dom';
import { ToListInfo } from '../../assets/type';
import { collectionsDecrease, collectionsIncrease, likesDecrease, likesIncrease, readChange } from '../../redux/actions';
import { useSelector } from '../../redux/types/hooks';

import './index.scss'

export default function NewsInfo(){
  const navigate = useNavigate()
  const back = () => {
    navigate(-1)
  }
  const dispatch = useDispatch()
  
  const location = useLocation()
  const { id,cate } = location.state as ToListInfo;
  
  const [news_content, setNewsContent] = useState<any>({})
  const [content, setContent] = useState('')
  const [editor, setEditor] = useState('')
  const [isLike, setIsLike] = useState(false)
  const [isCollection, setIsCollection] = useState(false)
  // let isFixed: true,

  let reg = /责任编辑/
  let user_name = useSelector(state => {
    return state.userLog.data.username
  });

  let lists = useSelector(state => state.pushRecLists)

  // 点击喜欢时发送请求
  async function ifLike() {
    let val = {
      user_name: user_name,
      news_id: id,
      action_time: Date.now(),
      action_type: `likes:${isLike}`,
    }

    let successData = await axios.post("/action", val).then(res => {
      return res
    })

    if (successData.status === 200) {
      setIsLike(!isLike)
      // 调用store中的actionChange函数控制次数的变化
      if (isLike === true) {
        dispatch(likesDecrease({ lists, id }))
      } else {
        dispatch(likesIncrease({ lists, id }))
      }
    } else {
      Toast.show({
        content: '加载数据失败',
      })
    }
  };

  // 点击收藏时发送请求
  async function ifCollection() {
    let val = {
      user_name: user_name,
      news_id: id,
      action_time: Date.now(),
      action_type: `collections::${isCollection}`,
    }

    let successData = await axios.post("/action", val).then(res => {
      return res
    })

    if (successData.status === 200) {
      setIsCollection(!isCollection)
      // 调用store中的actionChange函数控制次数的变化
      if (isCollection === true) {
        dispatch(collectionsDecrease({ lists, id }))
      } else {
        dispatch(collectionsIncrease({ lists, id }))
      }
    } else {
      Toast.show({
        content: '加载数据失败',
      })
    }
  };


  useEffect(() => {
    // 获取新闻详情
    (async function getNewsInfo () {
      let successData = await axios.get("/newsInfo?news_id=" + id + '&user_name=' + user_name).then(res => {
        return res
      })

      if (successData.status === 200) {
        setNewsContent(successData.data.data)
        setContent(successData.data.data.content.split(reg)[0])
        setEditor('责任编辑:' + successData.data.data.content.split(reg)[1])

        if (successData.data.data.likes === true) {
          setIsLike(true)
        } else {
          setIsLike(false)
        }
        if (successData.data.data.collections === true) {
          setIsCollection(true)
        } else {
          setIsCollection(false)
        }
      } else {
        Toast.show({
          content: '加载数据失败',
        })
      }
    })();

    // 发送action为read的请求
    (async function sendInfo() {
      let val = {
        user_name: user_name,
        news_id: id,
        action_time: Date.now(),
        action_type: 'read',
      }

      let successData = await axios.post("/action", val).then(res => {
        return res
      })

      if (successData.status === 200) {
        dispatch(readChange({ lists, id }))
      } else {
        Toast.show({
          content: '加载数据失败',
        })
      }
    })();
  },[])


  return (
    <>
      <NavBar back='返回' onBack={back}></NavBar>
        <div className="newsinfo-continer">
          <div className="newsTitle">
            {/* 大标题 */}
            <h1>{ news_content.title }</h1>
            {/* 子标题 */}
            <p>
              <span>发布时间：{ news_content.ctime}</span>
              <span>标签：{cate}</span>
            </p>
            <hr />
          </div>

          {/* 内容区域 */}
          <div className="content" dangerouslySetInnerHTML = {{ __html : content }}></div>
          <div className="editor" dangerouslySetInnerHTML = {{ __html : editor }}></div>

          <div id="action">
            <span>喜欢:
              <img src={require("../../assets/images/likes.png")} alt='likes' className={!isLike ? 'block-style' : 'hide-style'} onClick={ifLike} />
              <img src={require("../../assets/images/likes1.png")} alt='likes1' className={isLike?'block-style':'hide-style'} onClick={ifLike} />
            </span>
            <span>收藏:
            <img src={require("../../assets/images/collects.png")} alt='collects' className={!isCollection ? 'block-style' : 'hide-style'} onClick={ifCollection} />
            <img src={require("../../assets/images/collects1.png")} alt='collects1' className={isCollection ? 'block-style' : 'hide-style'} onClick={ifCollection} />
            </span>
          </div>

        </div>

        <div className="blank"></div>
    </>
  )
}

// fun-rec/codes/news_recsys/news_rec_web/vue2-fun-rec/src/views/NewsInfo.vue
<template>
  <div>
    <van-nav-bar left-text="返回" left-arrow @click-left="onClickLeft" :fixed='isFixed' />
    <div class="newsinfo-continer">
      <div class="newsTitle">
        <!--大标题-->
        <h1>{{ news_content.title }}</h1>
        <!--子标题-->
        <p>
          <span>发布时间：{{ news_content.ctime}}</span>
          <span>标签：{{cate}}</span>
        </p>
        <hr>
      </div>

      <!--内容区域-->
      <div class="content" v-html="content"></div>
      <div class="editor" v-html="editor"></div>

      <div id="action">
        <span>喜欢:
          <img src="../assets/images/likes.png" alt="" v-show="!islike" @click="iflike">
          <img src="../assets/images/likes1.png" alt="" v-show="islike" @click="iflike">
        </span>
        <span>收藏:
          <img src="../assets/images/collects.png" alt="" v-show="!iscollection" @click="ifcollection">
          <img src="../assets/images/collects1.png" alt="" v-show="iscollection" @click="ifcollection">
        </span>
      </div>

    </div>
    <div class="blank"></div>
  </div>

</template>

<script>
  import { Toast } from 'vant'

  export default {
    data() {
      return {
        // 获取路由地址的id,根据这个id来展示不同的数据。
        id: this.$route.params.id,
        news_content: [],
        content: '',
        editor: '',
        islike: false,
        iscollection: false,
        isFixed: true,
        cate: this.$route.params.cate
      }

    },
    methods: {
      // 返回上一页
      onClickLeft() {
        this.$router.go(-1);
      },

      // 获取新闻详情
      async getNewsInfo() {
        let reg = /责任编辑/;
        let user_name = this.$store.state.user.username;

        let successData
        if(this.$store.state.flag){
          successData = await this.axios.get("/recsys/news_detail?news_id=" + this.id + '&user_name=' + user_name).then(res => {
            return res
          })
        }else {
          successData = await this.axios.get("/newsInfo?news_id=" + this.id + '&user_name=' + user_name).then(res => {
            return res
          })
        }

        if (successData.status === 200) {
          this.news_content = successData.data.data
          this.content = this.news_content.content.split(reg)[0]
          this.editor = '责任编辑:' + this.news_content.content.split(reg)[1]
          if (successData.data.data.likes == true) {
            this.islike = true
          } else {
            this.islike = false
          }
          if (successData.data.data.collections == true) {
            this.iscollection = true
          } else {
            this.iscollection = false
          }
        } else {
          Toast('加载数据失败')
        }
      },

      // 发送action为read的请求
      async sendInfo() {
        var val = {
          user_name: this.$store.state.user.username,
          news_id: this.id,
          action_time: Date.now(),
          action_type: 'read',
        }

        let successData
        if(this.$store.state.flag){
          successData = await this.axios.post("/recsys/action", val).then(res => {
            return res
          })
        }else {
          successData = await this.axios.post("/action", val).then(res => {
            return res
          })
        }

        if (successData.status === 200) {} else {
          Toast('加载数据失败')
        }
      },

      // 点击喜欢时发送请求
      async iflike() {
        this.islike = !this.islike
        // 调用store中的actionChange函数控制次数的变化
        if(this.islike == true){
            this.$store.commit('actionChange', {type:'likes',id:this.id,num:1})
          }else{
            this.$store.commit('actionChange', {type:'likes',id:this.id,num:-1})
          }
        var val = {
          user_name: this.$store.state.user.username,
          news_id: this.id,
          action_time: Date.now(),
          action_type: `likes:${this.islike}`,
        }

        let successData
        if(this.$store.state.flag){
          successData = await this.axios.post("/recsys/action", val).then(res => {
            return res
          })
        }else {
          successData = await this.axios.post("/action", val).then(res => {
            return res
          })
        }

        if (successData.status === 200) {
        } else {
          Toast('加载数据失败')
        }
      },

      // 点击收藏时发送请求
      async ifcollection() {
        this.iscollection = !this.iscollection
        if(this.iscollection == true){
           this.$store.commit('actionChange', {type:'collections',id:this.id,num:1})
          }else{
            this.$store.commit('actionChange', {type:'collections',id:this.id,num:-1})
          }
        var val = {
          user_name: this.$store.state.user.username,
          news_id: this.id,
          action_time: Date.now(),
          action_type: `collections:${this.iscollection}`,
        }

        let successData
        if(this.$store.state.flag){
          successData = await this.axios.post("/recsys/action", val).then(res => {
            return res
          })
        }else {
          successData = await this.axios.post("/action", val).then(res => {
            return res
          })
        }

        if (successData.status === 200) {
        } else {
          Toast('加载数据失败')
        }
      }
    },

    // 创建页面时调用函数
    created() {
      this.getNewsInfo()
      this.sendInfo()
    },
  }
</script>

<style scoped>
    /* 标题 */
  .newsTitle {
    padding: 3.5rem 1.5rem 0 1.5rem;
  }

  /* 大标题 */
  .newsTitle h1 {
    text-align: center;
    color: rgb(77,79,83);;
    font-weight: 600;
    padding: 40px 0 20px 0;
    margin: 0;
    font-size: 1.5rem;
  }

  /* 副标题 */
  .newsTitle p {
    font-size: 12px;
    display: flex;
    justify-content: space-between;
    padding-top: 1rem;
    padding-bottom: 1rem;
    color: #4679e3;
  }

  /* 内容 距离底部padding 遮挡action */
  .newsinfo-continer{
    padding-bottom: 5rem;
    background-color: white;
  }

  /* 具体内容 */
  .content {
    font-size: 1rem;
    padding: 0 20px 20px 20px;
    text-indent: 2em;
    line-height: 2.2rem;
    /* 首行文本缩进 */
    color: rgb(28 27 29);
}

  /* 责任编辑 */
  .editor {
    font-size: 1rem;
    padding: 0 20px 0 20px;
    line-height: 2.2rem;
    text-align: end;
  }

  #action {
    /* margin: 20px 0 20px 0; */
    display: flex;
    justify-content: space-evenly;
  }

  #action>span {
    display: flex;
    padding-top: 2rem;
    padding-bottom: 2rem;
    font-size: 1rem;
  }

  .blank {
    width: 100vw;
    height: 50px;
    position: fixed;
    bottom: 0;
    background-color: white;
  }
</style>
